kind: source
spec:
  name: "lseg"
  registry: "grpc"
  path: "localhost:7777"
  tables: ['*']
  destinations: ["sqlite"]
  spec:
    username: "**CHANGE_ME**"
    password: "**CHANGE_ME**"
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.4.11"
  spec:
    connection_string: ./db.sqlite